### PR TITLE
Relax lower bound on bytestring

### PR DESCRIPTION
**Pull request by dpwiz**
Tested on GHC 8.10.

### CODE REVIEW

**Comment by emilypi** [comment]
Thanks @dpwiz, but `bytestring-0.11` has performance improvements that make it worth having as a lower bound. In particular, the offsets for bytestring, which are still tech debt in this library to clean up, are now unnecessary. I'm not in favor of lowering this bound.

**Comment by dpwiz** [comment]
Ugh, I've just found I need `text-1.x` too (something-something cross build for old ARMs) 😢 

Well, the performance of the system that can't be built is zero. We don't have `allow-older` in Cabal, are we?
Are there options besides maintaining a fork until the oldies can be ditched?

**Comment by emilypi** [comment]
`text-2.0` is _definitely_ the minimum support for this library unfortunately - we actually make use of it in places in the `Text` modules due to the fact that `decodeUtf8` is not partial anymore, so I don't know. What are your contraints? I'm happy to keep a branch open that you can pin to your `cabal.project` with relaxed constraints, but it'd take a little work on my part. I'm not impartial to doing that :)

**Comment by dpwiz** [comment]
Ok, I'll just use a fork for while. Sorry for bothering y'all (=

**Pull request closed without merging**
